Added package integrity verification for uninstallation

diff --git a/Website/Packages/neofetch/MOONBUILD b/Website/Packages/neofetch/MOONBUILD
--- a/Website/Packages/neofetch/MOONBUILD
+++ b/Website/Packages/neofetch/MOONBUILD
@@ -1,6 +1,4 @@
 #!/bin/bash
-cat > MOONBUILD << "EOF"
-#!/bin/bash
 MOONPKGNAME="neofetch"
 MOONPKGVERSION="7.1.0"
 MOONPKG="$MOONPKGNAME-$MOONPKGVERSION"
@@ -10,7 +8,7 @@ BUILDSCRIPTPID=""
 clean() {
    rm -rfv "$MOONPKG.tar.gz" "$MOONPKG.tar.gz.*" "$MOONPKG" 
 }
-trap 'echo -e "${YELLOW}Interrupted.${NC}"; clean' ERR
+trap 'echo -e "${YELLOW}Interrupted.${NC}"; clean' INT
 case $1 in
 	chkdeps)
         echo -e "${YELLOW}Checking for dependencies...${NC}"
@@ -65,7 +63,7 @@ case $1 in
                 echo -ne "\r${ORANGE}Downloading the package source tarball...${NC}"; sleep 0.2
             done &
             BUILDSCRIPTPID="$!"
-            wget "$SRC/$MOONPKG.tar.gz" &> /dev/null
+            wget "$SRC/$MOONPKGVERSION.tar.gz" -O "$MOONPKG.tar.gz" &> /dev/null
             trap 'echo "${ORANGE}An error was encountered while downloading the package.${NC}; kill $BUILDSCRIPTPID"' ERR; set +e
             trap - ERR
             kill $BUILDSCRIPTPID; echo -e "\n${WHITE}->Done!, now verifying package integrity."
@@ -121,10 +119,9 @@ case $1 in
             echo -e "${YELLOW}Installing ${WHITE}${MOONPKGNAME}...${NC}"; sleep 0.2
             pushd $MOONPKG
                 make PREFIX=/usr install && echo -e "${WHITE}->Done!${NC}"
-            popd
             echo -e "${YELLOW}Cleaning up...${NC}"; sleep 0.2
             clean 
-            trap 'echo -e "${YELLOW}Failed to clean up.${NC}; kill $BUILDSCRIPTPID; exit 1"' ERR
+            trap 'echo -e "${YELLOW}Failed to clean up.${NC}; kill $BUILDSCRIPTPID"' ERR
             set +e
         else
             while true; do
@@ -151,12 +148,12 @@ case $1 in
             popd &> /dev/null
             clean &> /dev/null
             trap 'echo -e "${YELLOW}Failed to clean up.${NC}; kill $BUILDSCRIPTPID; exit 1"' ERR
-            echo "\n${WHITE}Done!"; kill $BUILDSCRIPTPID
+            echo -e "\n${WHITE}Done!"; kill $BUILDSCRIPTPID
         fi
         trap - ERR
     ;;
 	uninstall)
-        echo -e "${ORANGE}Verifying package integrity.${NC}"
+        echo -e "${ORANGE}Verifying package integrity...${NC}"
         md5sum -c integrity.md5
         if [ "$?" -eq 0 ]; then echo -e "${YELLOW}Package integrity verified!${NC}"
         else
@@ -190,4 +187,3 @@ case $1 in
         fi
 	;;
 esac
-EOF
